{
 "title": "Rooms",
 "description": "Данные мониторинга рабочих мест",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Помещение 0 - Рабочее место 1",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    date_trunc('minute', timestamp - interval '10 hours') \r\n        - (extract(minute from timestamp - interval '10 hours')::int % 60) * interval '1 minute' AS time_bucket,\r\n    ROUND(100.0 * SUM(CASE WHEN free THEN 1 ELSE 0 END) / COUNT(*)::numeric, 2) AS free,\r\n    ROUND(100.0 * SUM(CASE WHEN NOT free THEN 1 ELSE 0 END) / COUNT(*)::numeric, 2) AS busy\r\nFROM\r\n    work_stations_statistics\r\nWHERE\r\n    work_station_id = '60319738-d379-4dd0-8268-c4cb32a45412'\r\n    AND timestamp - interval '10 hours' >= '2025-06-29'\r\n    AND timestamp - interval '10 hours' < '2025-06-30'\r\nGROUP BY\r\n    work_station_id,\r\n    time_bucket\r\nORDER BY\r\n    time_bucket;\r\n"
    }
   ]
  },
  {
   "title": "Процент занятости мест",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    work_station_id,\r\n    ROUND(100.0 * SUM(CASE WHEN free THEN 1 ELSE 0 END) / COUNT(*)::numeric, 2) AS free,\r\n    ROUND(100.0 * SUM(CASE WHEN NOT free THEN 1 ELSE 0 END) / COUNT(*)::numeric, 2) AS busy\r\nFROM\r\n    work_stations_statistics\r\nGROUP BY\r\n    work_station_id;"
    }
   ]
  },
  {
   "title": "Статистика по помещениям",
   "type": "table",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT ROUND(AVG(work_stations)) AS \"Рабочие места\", ROUND(AVG(persons)) AS \"Люди\", ROUND(AVG(sitting_persons)) AS \"Люди за рабочим местом\", ROUND(AVG(not_sitting_persons)) AS \"Люди не за рабочим местом\", ROUND(AVG(free_work_station)) AS \"Свободные места\", room_id AS \"id помещения\" FROM statistics GROUP BY room_id LIMIT 50 "
    },
    {
     "rawSql": "SELECT id, title AS \"Помещения\" FROM rooms LIMIT 50 "
    }
   ]
  }
 ]
}